[project]
name = "access-control-service"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic-settings",
    "passlib[bcrypt]==1.7.4",
    "bcrypt<4.0.0"
]

[tool.pytest.ini_options]
pythonpath = ["."]
